### ISSUE TITLE
Converter for non-ClipCC addons

### ISSUE THREAD

**Issue by qbjl** [Clipteam/clipcc-extension#1]
What if I have an extension and I want to easily port it to ClipCC but I don't have time? Well then, a converter might fix it. A converter would help with the ease of switching versions of extension types like Scratch Extension to ClipCC extension, so on and so forth. It would also get rid of wasted time replacing JSON with ClipCC.add. So please, could you add a converter? Thank you!

**Comment by SimonShiki** [comment]
Hello, ClipCC has supported the loading of Scratch extensions. We will also support storing such extensions within the project in a future update.
